stages:
  - build

nro-delegated-stats:
  stage: build
  image: $CI_REGISTRY/swe/gitlab-ci/sbt:1.3-2.12-jdk-8

  script:
    - sbt clean assembly 
  artifacts:
    paths:
      - target/scala-2.13/nro-delegated-stats.jar


